apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-container-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-container
  template:
    metadata:
      labels:
        app: my-python-container
    spec:
      containers:
      - name: my-python-container
        image: jash881/my-python-container
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"

        ports:
        - containerPort: 80
